"""Regenerate Web golden bytes using the preserved, unmodified Python MVP."""
from pathlib import Path
import sys
import json
from unittest.mock import patch
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'reference/python'))
from x3batch.core import encode_xth, export_xtch, discover, Settings
folder=ROOT/'web/tests/fixtures';folder.mkdir(parents=True,exist_ok=True)
rng=np.random.default_rng(2026)
manifest=[]
for name,w,h in [('x3',528,792),('padded',13,9),('all-levels',256,8)]:
    pixels=(np.tile(np.arange(256,dtype=np.uint8),(8,1)) if name=='all-levels'
            else rng.choice(np.array([0,85,170,255],dtype=np.uint8),(h,w)))
    (folder/f'{name}.gray').write_bytes(pixels.tobytes())
    (folder/f'{name}.xth').write_bytes(encode_xth(Image.fromarray(pixels)))
    manifest.append(dict(name=name,width=w,height=h))
(folder/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
input_folder=folder/'input';input_folder.mkdir(exist_ok=True)
# Exact target size: Canvas and Pillow do not need different resize filters.
a=np.zeros((792,528),dtype=np.uint8)
for i,g in enumerate([0,85,170,255]):a[:,i*132:(i+1)*132]=g
for n in [1,2]:
    im=Image.fromarray(np.roll(a,132*(n-1),axis=1)); im.save(input_folder/f'{n}.png')
with patch('x3batch.core.time.time',return_value=1700000000):
    export_xtch(discover([input_folder]),folder/'回帰テスト.xtch',Settings(dither='None'))
print('Golden XTH and XTCH generated by the unchanged Python reference.')
